packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@changesets/git': ^3.0.4
  '@eslint/js': ^9.39.1
  '@types/eslint': ^9.6.1
  "@types/node": ^24.10.1
  '@typescript-eslint/eslint-plugin': ^8.46.4
  '@typescript-eslint/parser': ^8.46.4
  "@vitejs/plugin-vue": ^6.0.1
  "@vue/tsconfig": ^0.8.1
  '@stylistic/stylelint-plugin': ^3.1.3
  '@manypkg/get-packages': ^3.0.0
  commitlint-plugin-function-rules: ^4.1.1
  cz-git: ^1.11.2
  chalk: ^5.4.1
  consola: ^3.4.2
  czg: ^1.11.1
  dayjs: ^1.11.13
  execa: ^9.6.0
  eslint: ^9.39.1
  eslint-config-turbo: ^2.6.1
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^61.2.1
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-n: ^17.23.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-unused-imports: ^4.3.0
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.5.1
  find-up: ^7.0.0
  globals: ^16.3.0
  jsonc-eslint-parser: ^2.4.1
  postcss: ^8.5.6
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.0
  postcss-import: ^16.1.1
  postcss-preset-env: ^10.2.4
  ora: ^8.2.0
  pkg-types: ^2.2.0
  postcss-scss: ^4.0.9
  rimraf: ^6.1.0
  prettier: ^3.6.2
  stylelint: ^16.21.0
  stylelint-config-recess-order: ^6.1.0
  stylelint-config-recommended: ^17.0.0
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^38.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.12.1
  typescript: ~5.9.3
  unbuild: ^3.6.1
  vite: npm:rolldown-vite@7.2.5
  vue: ^3.5.24
  vue-eslint-parser: ^10.2.0
  vue-tsc: ^3.1.4
